### ISSUE TITLE
The parsing can get into endless loop, and abort with StackOverflowException

### ISSUE THREAD

**Issue by cyborgyn** [kekyo/IL2C#105]
If we try to transpile a _struct_, where one of the _static_ **fields** are themselves, the transpilation fails with _StackOverflowException_.
Example:
```
    public struct MyStruct
    {
        private int value;

        public static MyStruct Default = new MyStruct(1000);

        public MyStruct(int value) { this.value = value; }
    }
```

**Comment by kekyo** [comment]
@cyborgyn The static field initializer (translated type initializer) implicitly depends correct initializing sequence graph.
I don't check a requirements on ECMA-335 and don't have much insight now...

#97 and #98 related, first related issue is #4

If we don't any resolve correcting, may cause the binary touch uninitialized data...?

**Comment by kekyo** [comment]
Bit related? #85

**Comment by kekyo** [comment]
@cyborgyn Sorry for the very delay. I understood #100 work and imported it with cherry-pick. https://github.com/kekyo/IL2C/commit/2cbb6f1da780acb289fb9f98d7b4adda99fd06c3
