### ISSUE TITLE
Output settings for generated c source files

### ISSUE THREAD

**Issue by chameleonhead** [kekyo/IL2C#64]
Output c source file contains path info where I compile.
like 

```
#line 9 "C:\\...\\IL2CTestProjects\\Test1\\Program.cs"
```

Is there any settings or any way to not show the path information?

I'm using Windows 10 downloading from NuGet.

**Comment by kekyo** [comment]
Did you mean:
1. The path is wrong (not exists path or contains invalid chars in path string).
2. You wanna hide the path.

You can hide the path with "IL2CDebugInformation" property in the PropertyGroup/csproj.
It's optional value, you can choice and apply from these values:
```csharp
    public enum DebugInformationOptions
    {
        None,
        CommentOnly,
        Full
    }
```

The None value will not write any debug directives.
The CommentOnly value will write [additional comments likely it](https://github.com/kekyo/IL2C/blob/e35762df2769a55fc1251c3604f0c4165537c3d0/samples/AzureSphere/Mt3620App/src/MT3620Blink/MT3620Blink/GpioOutput.c#L66). It will not write line directives.
The Full value is same as your seeing, includes line directives.

[See property example]( https://github.com/kekyo/IL2C/blob/e35762df2769a55fc1251c3604f0c4165537c3d0/samples/AzureSphere/MT3620Blink/MT3620Blink.csproj#L29)

I recommend the CommentOnly if you don't want to line debugging.

**Comment by chameleonhead** [comment]
Thank you for response.

I meant I just wanted to hide path for uploading source code in public. I understand the settings, I'll use CommentOnly this time. Are there any other generate time options?

**Comment by kekyo** [comment]
Yes, it's overall property definitions by the MSBuild script (inside IL2C.Build package): https://github.com/kekyo/IL2C/blob/master/IL2C.Tasks/build/IL2C.Build.targets

* IL2COutputPath: Will place generated codes directory path.
* IL2CDebugInformation: Already explained.
* IL2CReadSymbols: IL2C will read symbol file (*.pdb, mdb...). The IL2C will produce better symbolic naming using these informations.
* IL2CEnableCpp: IL2C will apply *.cpp extension each output source codes. It DOESN'T mean switching to use C++ syntax.
* IL2CEnableBundler: IL2C will produce the bundler source code. It combines all source codes (*.c) into single bindler source code (Implementation is simply, apply include directive each all source code).

**Comment by chameleonhead** [comment]
Thank you very much for explanation. I'll try it.
