### ISSUE TITLE
错误	C2371	“System_Object_VTABLE_DECL__”: 重定义；不同的基类型

### ISSUE THREAD

**Issue by ohacn** [kekyo/IL2C#71]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C2371	“System_Object_VTABLE_DECL__”: 重定义；不同的基类型	GettingStartedIL2CMain	c:\users\i\desktop\il2c-master\il2c.runtime\include\system\eventargs.h	16	

typedef struct System_Object_VTABLE_DECL__ System_EventArgs_VTABLE_DECL__;

严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C2371	“System_EventArgs_VTABLE_DECL__”: 重定义；不同的基类型	GettingStartedIL2CMain	c:\users\i\desktop\il2c-master\il2c.runtime\include\system\unhandledexceptioneventargs.h	16	

typedef struct System_EventArgs_VTABLE_DECL__ System_UnhandledExceptionEventArgs_VTABLE_DECL__;

**Comment by kekyo** [comment]
Thanks report @ohacn, I fixed it at 6275d701c8b47fc1c0ecceb4d3cc9557d3abffe6.
Would you try it after CI passed?

**Comment by kekyo** [comment]
Fixed.
